# # docker-compose.yml
# version: '3.8'

# services:
#   php-apache:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: php-container
#     ports:
#       - "8080:80"
#     volumes:
#       - ./project:/var/www/html  #Cập nhật thay đổi ở index.php

version: '3.8'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-container
    ports:
      - "8081:80"
    volumes:
      - ./project:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: